version: '3.9'
services:
  trooper-ms-gateway:
    container_name: ms-gateway
    build: ./
    ports:
      - 5000:5000
    volumes:
      - ./:/app/ms-gateway
    environment:
      - PORT=5000
      - PRODUCT_HOST=ms-product
      - CATEGORY_HOST=ms-product
      - ACCOUNT_HOST=ms-account
      - ORDER_HOST=ms-order
      - PAYMENT_HOST=ms-payment
      - REDIS_HOST=redis-ms-gateway
      - JWT_SECRET=MTk4OGExOTZkMWYyOWZjZjlmOTcwMWVjZWRjMzc1MzZkOGM0MmFjMjQ0NjcyZjIzZDQwOGU4YTQ1YWQ3NTRjZA==
  
  redis-ms-gateway:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - redis-gateway-volume-docker:/data

  rabbit-ms-gateway:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit-gateway-volume-data:/var/lib/rabbitmq/
      - rabbit-gateway-volume-log:/var/log/rabbitmq

volumes:
  redis-gateway-volume-docker:
  rabbit-gateway-volume-data:
  rabbit-gateway-volume-log:

networks: 
  default:
    name: trooper-network
    external: true
    